image: ubuntu
platform: Any CPU

environment:
  CODACY_PROJECT_TOKEN:
    secure: FN4dD7OPIgT/+uC2pwLf2KPqk0XuHrMwcOyIWSMwh8jxEEWrNOi6/PKbDFJ3HNFo
  CC_TEST_REPORTER_ID:
    secure: /gLeOkVSqSjiewfTq8ANDi0JG+JaIAhxkCroiwtMsf78xVNgfHCcXoUkchPGfihA1PQJ5e2zMrcQ+zj/3EnavpStWz8A0RwWSa52z0Qz+pQ=

stack: "node 14"

install:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # install modules
  - sh: npm install
  - sh: npm install -g mocha c8

before_test:
  # Download codeclimate test report
  - sh: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./codeclimate-test-reporter
  - sh: chmod +x ./codeclimate-test-reporter

test_script:
  - c8 --reporter=lcov mocha --timeout 20000

after_test:
  # Send test result to codeclimate
  - sh: ./codeclimate-test-reporter before-build
  - sh: ./codeclimate-test-reporter after-build -t lcov --exit-code $?
  # Send test result to Codacy
  - sh: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage/lcov.info

# Don't actually build.
build: off
